/**
 * Sample Playwright test generated by Autotest AI Generator.
 *
 * This is an example of what the AI produces from a natural language prompt.
 * Prompt: "Test the login form with invalid credentials and verify error message"
 * Target: https://example.com/login
 *
 * Generated by: Claude + Playwright MCP
 */

import { test, expect } from "@playwright/test";

test.describe("Login Form — Invalid Credentials", () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the login page
    await page.goto("https://example.com/login");

    // Wait for the login form to be fully loaded
    await page.waitForSelector("form", { state: "visible" });
  });

  test("should show error message for invalid email and password", async ({
    page,
  }) => {
    // Fill in invalid email
    const emailInput = page.locator(
      'input[name="email"], input[type="email"], [placeholder*="email" i]'
    );
    await emailInput.fill("invalid@wrong.com");

    // Fill in invalid password
    const passwordInput = page.locator(
      'input[name="password"], input[type="password"], [placeholder*="password" i]'
    );
    await passwordInput.fill("wrongpassword123");

    // Click the Sign In / Submit button
    const submitButton = page.locator(
      'button[type="submit"], button:has-text("Sign In"), button:has-text("Log In")'
    );
    await submitButton.click();

    // Wait for the error message to appear
    const errorMessage = page.locator(
      '[role="alert"], .error-message, .alert-danger, [data-testid="error"]'
    );
    await expect(errorMessage).toBeVisible({ timeout: 5000 });

    // Verify the error message contains relevant text
    await expect(errorMessage).toContainText(/invalid|incorrect|wrong/i);

    // Verify we are still on the login page (no redirect)
    expect(page.url()).toContain("/login");

    // Verify the form is still visible (not cleared)
    await expect(emailInput).toBeVisible();
    await expect(passwordInput).toBeVisible();
  });

  test("should show validation errors for empty form submission", async ({
    page,
  }) => {
    // Click submit without filling any fields
    const submitButton = page.locator(
      'button[type="submit"], button:has-text("Sign In"), button:has-text("Log In")'
    );
    await submitButton.click();

    // Verify validation messages appear
    // Check for HTML5 validation or custom validation messages
    const emailInput = page.locator(
      'input[name="email"], input[type="email"]'
    );
    const passwordInput = page.locator(
      'input[name="password"], input[type="password"]'
    );

    // At least one validation indicator should be present
    const hasValidation = await page
      .locator(
        ".field-error, .validation-error, .invalid-feedback, :invalid"
      )
      .count();
    expect(hasValidation).toBeGreaterThan(0);

    // Should still be on login page
    expect(page.url()).toContain("/login");
  });

  test("should show error for valid email but wrong password", async ({
    page,
  }) => {
    // Use a valid-looking email with wrong password
    const emailInput = page.locator(
      'input[name="email"], input[type="email"]'
    );
    await emailInput.fill("registered-user@example.com");

    const passwordInput = page.locator(
      'input[name="password"], input[type="password"]'
    );
    await passwordInput.fill("definitely-wrong-password");

    const submitButton = page.locator(
      'button[type="submit"], button:has-text("Sign In")'
    );
    await submitButton.click();

    // Error should appear
    const errorMessage = page.locator(
      '[role="alert"], .error-message, .alert-danger'
    );
    await expect(errorMessage).toBeVisible({ timeout: 5000 });

    // Password field should be cleared (common security practice)
    // or the form should remain visible for retry
    await expect(
      page.locator('input[name="email"], input[type="email"]')
    ).toBeVisible();
  });
});
